//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStatisticGroupe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentStatisticsEDMContainer : DbContext
    {
        public StudentStatisticsEDMContainer()
            : base("name=StudentStatisticsEDMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> GroupSet { get; set; }
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Teacher> TeacherSet { get; set; }
        public virtual DbSet<DisciplineSet> DisciplineSetSet { get; set; }
        public virtual DbSet<StudentStatistic> StudentStatisticSet { get; set; }
        public virtual DbSet<Point> PointSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
    }
}
