//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentStatisticGroupe
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentStatistic
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public string Type { get; set; }
        public string NameStudent { get; set; }
        public string NameTeacher { get; set; }
        public string Point { get; set; }
        public string Comment { get; set; }
    }
}
